<?php

namespace Database\Seeders;

use App\Models\Currency;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CurrencySeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Currency::insert([
            [
                'currency_id' => 1,
                'name' => 'United Arab Emirates Dirham',
                'code' => 'AED',
                'notes' => null,
            ],
            [
                'currency_id' => 2,
                'name' => 'Afghan Afghani',
                'code' => 'AFN',
                'notes' => null,
            ],
            [
                'currency_id' => 3,
                'name' => 'Albanian Lek',
                'code' => 'ALL',
                'notes' => null,
            ],
            [
                'currency_id' => 4,
                'name' => 'Armenian Dram',
                'code' => 'AMD',
                'notes' => null,
            ],
            [
                'currency_id' => 5,
                'name' => 'Netherlands Antillean Guilder',
                'code' => 'ANG',
                'notes' => null,
            ],
            [
                'currency_id' => 6,
                'name' => 'Angolan Kwanza',
                'code' => 'AOA',
                'notes' => null,
            ],
            [
                'currency_id' => 7,
                'name' => 'Argentine Peso',
                'code' => 'ARS',
                'notes' => null,
            ],
            [
                'currency_id' => 8,
                'name' => 'Australian Dollar',
                'code' => 'AUD',
                'notes' => null,
            ],
            [
                'currency_id' => 9,
                'name' => 'Aruban Florin',
                'code' => 'AWG',
                'notes' => null,
            ],
            [
                'currency_id' => 10,
                'name' => 'Azerbaijani Manat',
                'code' => 'AZN',
                'notes' => null,
            ],
            [
                'currency_id' => 11,
                'name' => 'Bosnia-Herzegovina Convertible Mark',
                'code' => 'BAM',
                'notes' => null,
            ],
            [
                'currency_id' => 12,
                'name' => 'Barbadian Dollar',
                'code' => 'BBD',
                'notes' => null,
            ],
            [
                'currency_id' => 13,
                'name' => 'Bangladeshi Taka',
                'code' => 'BDT',
                'notes' => null,
            ],
            [
                'currency_id' => 14,
                'name' => 'Bulgarian Lev',
                'code' => 'BGN',
                'notes' => null,
            ],
            [
                'currency_id' => 15,
                'name' => 'Bahraini Dinar',
                'code' => 'BHD',
                'notes' => null,
            ],
            [
                'currency_id' => 16,
                'name' => 'Burundian Franc',
                'code' => 'BIF',
                'notes' => null,
            ],
            [
                'currency_id' => 17,
                'name' => 'Bermudan Dollar',
                'code' => 'BMD',
                'notes' => null,
            ],
            [
                'currency_id' => 18,
                'name' => 'Brunei Dollar',
                'code' => 'BND',
                'notes' => null,
            ],
            [
                'currency_id' => 19,
                'name' => 'Bolivian Boliviano',
                'code' => 'BOB',
                'notes' => null,
            ],
            [
                'currency_id' => 20,
                'name' => 'Brazilian Real',
                'code' => 'BRL',
                'notes' => null,
            ],
            [
                'currency_id' => 21,
                'name' => 'Bahamian Dollar',
                'code' => 'BSD',
                'notes' => null,
            ],
            [
                'currency_id' => 22,
                'name' => 'Bitcoin',
                'code' => 'BTC',
                'notes' => null,
            ],
            [
                'currency_id' => 23,
                'name' => 'Bhutanese Ngultrum',
                'code' => 'BTN',
                'notes' => null,
            ],
            [
                'currency_id' => 24,
                'name' => 'Botswanan Pula',
                'code' => 'BWP',
                'notes' => null,
            ],
            [
                'currency_id' => 25,
                'name' => 'Belarusian Ruble',
                'code' => 'BYR',
                'notes' => null,
            ],
            [
                'currency_id' => 26,
                'name' => 'Belize Dollar',
                'code' => 'BZD',
                'notes' => null,
            ],
            [
                'currency_id' => 27,
                'name' => 'Canadian Dollar',
                'code' => 'CAD',
                'notes' => null,
            ],
            [
                'currency_id' => 28,
                'name' => 'Congolese Franc',
                'code' => 'CDF',
                'notes' => null,
            ],
            [
                'currency_id' => 29,
                'name' => 'Swiss Franc',
                'code' => 'CHF',
                'notes' => null,
            ],
            [
                'currency_id' => 30,
                'name' => 'Chilean Unit of Account (UF)',
                'code' => 'CLF',
                'notes' => null,
            ],
            [
                'currency_id' => 31,
                'name' => 'Chilean Peso',
                'code' => 'CLP',
                'notes' => null,
            ],
            [
                'currency_id' => 32,
                'name' => 'Chinese Yuan',
                'code' => 'CNY',
                'notes' => null,
            ],
            [
                'currency_id' => 33,
                'name' => 'Colombian Peso',
                'code' => 'COP',
                'notes' => null,
            ],
            [
                'currency_id' => 34,
                'name' => 'Costa Rican Colón',
                'code' => 'CRC',
                'notes' => null,
            ],
            [
                'currency_id' => 35,
                'name' => 'Cuban Convertible Peso',
                'code' => 'CUC',
                'notes' => null,
            ],
            [
                'currency_id' => 36,
                'name' => 'Cuban Peso',
                'code' => 'CUP',
                'notes' => null,
            ],
            [
                'currency_id' => 37,
                'name' => 'Cape Verdean Escudo',
                'code' => 'CVE',
                'notes' => null,
            ],
            [
                'currency_id' => 38,
                'name' => 'Czech Republic Koruna',
                'code' => 'CZK',
                'notes' => null,
            ],
            [
                'currency_id' => 39,
                'name' => 'Djiboutian Franc',
                'code' => 'DJF',
                'notes' => null,
            ],
            [
                'currency_id' => 40,
                'name' => 'Danish Krone',
                'code' => 'DKK',
                'notes' => null,
            ],
            [
                'currency_id' => 41,
                'name' => 'Dominican Peso',
                'code' => 'DOP',
                'notes' => null,
            ],
            [
                'currency_id' => 42,
                'name' => 'Algerian Dinar',
                'code' => 'DZD',
                'notes' => null,
            ],
            [
                'currency_id' => 43,
                'name' => 'Estonian Kroon',
                'code' => 'EEK',
                'notes' => null,
            ],
            [
                'currency_id' => 44,
                'name' => 'Egyptian Pound',
                'code' => 'EGP',
                'notes' => null,
            ],
            [
                'currency_id' => 45,
                'name' => 'Eritrean Nakfa',
                'code' => 'ERN',
                'notes' => null,
            ],
            [
                'currency_id' => 46,
                'name' => 'Ethiopian Birr',
                'code' => 'ETB',
                'notes' => null,
            ],
            [
                'currency_id' => 47,
                'name' => 'Euro',
                'code' => 'EUR',
                'notes' => null,
            ],
            [
                'currency_id' => 48,
                'name' => 'Fijian Dollar',
                'code' => 'FJD',
                'notes' => null,
            ],
            [
                'currency_id' => 49,
                'name' => 'Falkland Islands Pound',
                'code' => 'FKP',
                'notes' => null,
            ],
            [
                'currency_id' => 50,
                'name' => 'British Pound Sterling',
                'code' => 'GBP',
                'notes' => null,
            ],
            [
                'currency_id' => 51,
                'name' => 'Georgian Lari',
                'code' => 'GEL',
                'notes' => null,
            ],
            [
                'currency_id' => 52,
                'name' => 'Guernsey Pound',
                'code' => 'GGP',
                'notes' => null,
            ],
            [
                'currency_id' => 53,
                'name' => 'Ghanaian Cedi',
                'code' => 'GHS',
                'notes' => null,
            ],
            [
                'currency_id' => 54,
                'name' => 'Gibraltar Pound',
                'code' => 'GIP',
                'notes' => null,
            ],
            [
                'currency_id' => 55,
                'name' => 'Gambian Dalasi',
                'code' => 'GMD',
                'notes' => null,
            ],
            [
                'currency_id' => 56,
                'name' => 'Guinean Franc',
                'code' => 'GNF',
                'notes' => null,
            ],
            [
                'currency_id' => 57,
                'name' => 'Guatemalan Quetzal',
                'code' => 'GTQ',
                'notes' => null,
            ],
            [
                'currency_id' => 58,
                'name' => 'Guyanaese Dollar',
                'code' => 'GYD',
                'notes' => null,
            ],
            [
                'currency_id' => 59,
                'name' => 'Hong Kong Dollar',
                'code' => 'HKD',
                'notes' => null,
            ],
            [
                'currency_id' => 60,
                'name' => 'Honduran Lempira',
                'code' => 'HNL',
                'notes' => null,
            ],
            [
                'currency_id' => 61,
                'name' => 'Croatian Kuna',
                'code' => 'HRK',
                'notes' => null,
            ],
            [
                'currency_id' => 62,
                'name' => 'Haitian Gourde',
                'code' => 'HTG',
                'notes' => null,
            ],
            [
                'currency_id' => 63,
                'name' => 'Hungarian Forint',
                'code' => 'HUF',
                'notes' => null,
            ],
            [
                'currency_id' => 64,
                'name' => 'Indonesian Rupiah',
                'code' => 'IDR',
                'notes' => null,
            ],
            [
                'currency_id' => 65,
                'name' => 'Israeli New Sheqel',
                'code' => 'ILS',
                'notes' => null,
            ],
            [
                'currency_id' => 66,
                'name' => 'Manx pound',
                'code' => 'IMP',
                'notes' => null,
            ],
            [
                'currency_id' => 67,
                'name' => 'Indian Rupee',
                'code' => 'INR',
                'notes' => null,
            ],
            [
                'currency_id' => 68,
                'name' => 'Iraqi Dinar',
                'code' => 'IQD',
                'notes' => null,
            ],
            [
                'currency_id' => 69,
                'name' => 'Iranian Rial',
                'code' => 'IRR',
                'notes' => null,
            ],
            [
                'currency_id' => 70,
                'name' => 'Icelandic Króna',
                'code' => 'ISK',
                'notes' => null,
            ],
            [
                'currency_id' => 71,
                'name' => 'Jersey Pound',
                'code' => 'JEP',
                'notes' => null,
            ],
            [
                'currency_id' => 72,
                'name' => 'Jamaican Dollar',
                'code' => 'JMD',
                'notes' => null,
            ],
            [
                'currency_id' => 73,
                'name' => 'Jordanian Dinar',
                'code' => 'JOD',
                'notes' => null,
            ],
            [
                'currency_id' => 74,
                'name' => 'Japanese Yen',
                'code' => 'JPY',
                'notes' => null,
            ],
            [
                'currency_id' => 75,
                'name' => 'Kenyan Shilling',
                'code' => 'KES',
                'notes' => null,
            ],
            [
                'currency_id' => 76,
                'name' => 'Kyrgystani Som',
                'code' => 'KGS',
                'notes' => null,
            ],
            [
                'currency_id' => 77,
                'name' => 'Cambodian Riel',
                'code' => 'KHR',
                'notes' => null,
            ],
            [
                'currency_id' => 78,
                'name' => 'Comorian Franc',
                'code' => 'KMF',
                'notes' => null,
            ],
            [
                'currency_id' => 79,
                'name' => 'North Korean Won',
                'code' => 'KPW',
                'notes' => null,
            ],
            [
                'currency_id' => 80,
                'name' => 'South Korean Won',
                'code' => 'KRW',
                'notes' => null,
            ],
            [
                'currency_id' => 81,
                'name' => 'Kuwaiti Dinar',
                'code' => 'KWD',
                'notes' => null,
            ],
            [
                'currency_id' => 82,
                'name' => 'Cayman Islands Dollar',
                'code' => 'KYD',
                'notes' => null,
            ],
            [
                'currency_id' => 83,
                'name' => 'Kazakhstani Tenge',
                'code' => 'KZT',
                'notes' => null,
            ],
            [
                'currency_id' => 84,
                'name' => 'Laotian Kip',
                'code' => 'LAK',
                'notes' => null,
            ],
            [
                'currency_id' => 85,
                'name' => 'Lebanese Pound',
                'code' => 'LBP',
                'notes' => null,
            ],
            [
                'currency_id' => 86,
                'name' => 'Sri Lankan Rupee',
                'code' => 'LKR',
                'notes' => null,
            ],
            [
                'currency_id' => 87,
                'name' => 'Liberian Dollar',
                'code' => 'LRD',
                'notes' => null,
            ],
            [
                'currency_id' => 88,
                'name' => 'Lesotho Loti',
                'code' => 'LSL',
                'notes' => null,
            ],
            [
                'currency_id' => 89,
                'name' => 'Lithuanian Litas',
                'code' => 'LTL',
                'notes' => null,
            ],
            [
                'currency_id' => 90,
                'name' => 'Latvian Lats',
                'code' => 'LVL',
                'notes' => null,
            ],
            [
                'currency_id' => 91,
                'name' => 'Libyan Dinar',
                'code' => 'LYD',
                'notes' => null,
            ],
            [
                'currency_id' => 92,
                'name' => 'Moroccan Dirham',
                'code' => 'MAD',
                'notes' => null,
            ],
            [
                'currency_id' => 93,
                'name' => 'Moldovan Leu',
                'code' => 'MDL',
                'notes' => null,
            ],
            [
                'currency_id' => 94,
                'name' => 'Malagasy Ariary',
                'code' => 'MGA',
                'notes' => null,
            ],
            [
                'currency_id' => 95,
                'name' => 'Macedonian Denar',
                'code' => 'MKD',
                'notes' => null,
            ],
            [
                'currency_id' => 96,
                'name' => 'Myanma Kyat',
                'code' => 'MMK',
                'notes' => null,
            ],
            [
                'currency_id' => 97,
                'name' => 'Mongolian Tugrik',
                'code' => 'MNT',
                'notes' => null,
            ],
            [
                'currency_id' => 98,
                'name' => 'Macanese Pataca',
                'code' => 'MOP',
                'notes' => null,
            ],
            [
                'currency_id' => 99,
                'name' => 'Mauritanian Ouguiya',
                'code' => 'MRO',
                'notes' => null,
            ],
            [
                'currency_id' => 100,
                'name' => 'Mauritian Rupee',
                'code' => 'MUR',
                'notes' => null,
            ],
            [
                'currency_id' => 101,
                'name' => 'Maldivian Rufiyaa',
                'code' => 'MVR',
                'notes' => null,
            ],
            [
                'currency_id' => 102,
                'name' => 'Malawian Kwacha',
                'code' => 'MWK',
                'notes' => null,
            ],
            [
                'currency_id' => 103,
                'name' => 'Mexican Peso',
                'code' => 'MXN',
                'notes' => null,
            ],
            [
                'currency_id' => 104,
                'name' => 'Malaysian Ringgit',
                'code' => 'MYR',
                'notes' => null,
            ],
            [
                'currency_id' => 105,
                'name' => 'Mozambican Metical',
                'code' => 'MZN',
                'notes' => null,
            ],
            [
                'currency_id' => 106,
                'name' => 'Namibian Dollar',
                'code' => 'NAD',
                'notes' => null,
            ],
            [
                'currency_id' => 107,
                'name' => 'Nigerian Naira',
                'code' => 'NGN',
                'notes' => null,
            ],
            [
                'currency_id' => 108,
                'name' => 'Nicaraguan Córdoba',
                'code' => 'NIO',
                'notes' => null,
            ],
            [
                'currency_id' => 109,
                'name' => 'Norwegian Krone',
                'code' => 'NOK',
                'notes' => null,
            ],
            [
                'currency_id' => 110,
                'name' => 'Nepalese Rupee',
                'code' => 'NPR',
                'notes' => null,
            ],
            [
                'currency_id' => 111,
                'name' => 'New Zealand Dollar',
                'code' => 'NZD',
                'notes' => null,
            ],
            [
                'currency_id' => 112,
                'name' => 'Omani Rial',
                'code' => 'OMR',
                'notes' => null,
            ],
            [
                'currency_id' => 113,
                'name' => 'Panamanian Balboa',
                'code' => 'PAB',
                'notes' => null,
            ],
            [
                'currency_id' => 114,
                'name' => 'Peruvian Nuevo Sol',
                'code' => 'PEN',
                'notes' => null,
            ],
            [
                'currency_id' => 115,
                'name' => 'Papua New Guinean Kina',
                'code' => 'PGK',
                'notes' => null,
            ],
            [
                'currency_id' => 116,
                'name' => 'Philippine Peso',
                'code' => 'PHP',
                'notes' => null,
            ],
            [
                'currency_id' => 117,
                'name' => 'Pakistani Rupee',
                'code' => 'PKR',
                'notes' => null,
            ],
            [
                'currency_id' => 118,
                'name' => 'Polish Zloty',
                'code' => 'PLN',
                'notes' => null,
            ],
            [
                'currency_id' => 119,
                'name' => 'Paraguayan Guarani',
                'code' => 'PYG',
                'notes' => null,
            ],
            [
                'currency_id' => 120,
                'name' => 'Qatari Rial',
                'code' => 'QAR',
                'notes' => null,
            ],
            [
                'currency_id' => 121,
                'name' => 'Romanian Leu',
                'code' => 'RON',
                'notes' => null,
            ],
            [
                'currency_id' => 122,
                'name' => 'Serbian Dinar',
                'code' => 'RSD',
                'notes' => null,
            ],
            [
                'currency_id' => 123,
                'name' => 'Russian Ruble',
                'code' => 'RUB',
                'notes' => null,
            ],
            [
                'currency_id' => 124,
                'name' => 'Rwandan Franc',
                'code' => 'RWF',
                'notes' => null,
            ],
            [
                'currency_id' => 125,
                'name' => 'Saudi Riyal',
                'code' => 'SAR',
                'notes' => null,
            ],
            [
                'currency_id' => 126,
                'name' => 'Solomon Islands Dollar',
                'code' => 'SBD',
                'notes' => null,
            ],
            [
                'currency_id' => 127,
                'name' => 'Seychellois Rupee',
                'code' => 'SCR',
                'notes' => null,
            ],
            [
                'currency_id' => 128,
                'name' => 'Sudanese Pound',
                'code' => 'SDG',
                'notes' => null,
            ],
            [
                'currency_id' => 129,
                'name' => 'Swedish Krona',
                'code' => 'SEK',
                'notes' => null,
            ],
            [
                'currency_id' => 130,
                'name' => 'Singapore Dollar',
                'code' => 'SGD',
                'notes' => null,
            ],
            [
                'currency_id' => 131,
                'name' => 'Saint Helena Pound',
                'code' => 'SHP',
                'notes' => null,
            ],
            [
                'currency_id' => 132,
                'name' => 'Sierra Leonean Leone',
                'code' => 'SLL',
                'notes' => null,
            ],
            [
                'currency_id' => 133,
                'name' => 'Somali Shilling',
                'code' => 'SOS',
                'notes' => null,
            ],
            [
                'currency_id' => 134,
                'name' => 'Surinamese Dollar',
                'code' => 'SRD',
                'notes' => null,
            ],
            [
                'currency_id' => 135,
                'name' => 'São Tomé and Príncipe Dobra',
                'code' => 'STD',
                'notes' => null,
            ],
            [
                'currency_id' => 136,
                'name' => 'Salvadoran Colón',
                'code' => 'SVC',
                'notes' => null,
            ],
            [
                'currency_id' => 137,
                'name' => 'Syrian Pound',
                'code' => 'SYP',
                'notes' => null,
            ],
            [
                'currency_id' => 138,
                'name' => 'Swazi Lilangeni',
                'code' => 'SZL',
                'notes' => null,
            ],
            [
                'currency_id' => 139,
                'name' => 'Thai Baht',
                'code' => 'THB',
                'notes' => null,
            ],
            [
                'currency_id' => 140,
                'name' => 'Tajikistani Somoni',
                'code' => 'TJS',
                'notes' => null,
            ],
            [
                'currency_id' => 141,
                'name' => 'Turkmenistani Manat',
                'code' => 'TMT',
                'notes' => null,
            ],
            [
                'currency_id' => 142,
                'name' => 'Tunisian Dinar',
                'code' => 'TND',
                'notes' => null,
            ],
            [
                'currency_id' => 143,
                'name' => "Tongan Pa'anga",
                'code' => 'TOP',
                'notes' => null,
            ],
            [
                'currency_id' => 144,
                'name' => 'Turkish Lira',
                'code' => 'TRY',
                'notes' => null,
            ],
            [
                'currency_id' => 145,
                'name' => 'Trinidad and Tobago Dollar',
                'code' => 'TTD',
                'notes' => null,
            ],
            [
                'currency_id' => 146,
                'name' => 'New Taiwan Dollar',
                'code' => 'TWD',
                'notes' => null,
            ],
            [
                'currency_id' => 147,
                'name' => 'Tanzanian Shilling',
                'code' => 'TZS',
                'notes' => null,
            ],
            [
                'currency_id' => 148,
                'name' => 'Ukrainian Hryvnia',
                'code' => 'UAH',
                'notes' => null,
            ],
            [
                'currency_id' => 149,
                'name' => 'Ugandan Shilling',
                'code' => 'UGX',
                'notes' => null,
            ],
            [
                'currency_id' => 150,
                'name' => 'United States Dollar',
                'code' => 'USD',
                'notes' => null,
            ],
            [
                'currency_id' => 151,
                'name' => 'Uruguayan Peso',
                'code' => 'UYU',
                'notes' => null,
            ],
            [
                'currency_id' => 152,
                'name' => 'Uzbekistan Som',
                'code' => 'UZS',
                'notes' => null,
            ],
            [
                'currency_id' => 153,
                'name' => 'Venezuelan Bolívar Fuerte',
                'code' => 'VEF',
                'notes' => null,
            ],
            [
                'currency_id' => 154,
                'name' => 'Vietnamese Dong',
                'code' => 'VND',
                'notes' => null,
            ],
            [
                'currency_id' => 155,
                'name' => 'Vanuatu Vatu',
                'code' => 'VUV',
                'notes' => null,
            ],
            [
                'currency_id' => 156,
                'name' => 'Samoan Tala',
                'code' => 'WST',
                'notes' => null,
            ],
            [
                'currency_id' => 157,
                'name' => 'CFA Franc BEAC',
                'code' => 'XAF',
                'notes' => null,
            ],
            [
                'currency_id' => 158,
                'name' => 'Silver (troy ounce)',
                'code' => 'XAG',
                'notes' => null,
            ],
            [
                'currency_id' => 159,
                'name' => 'Gold (troy ounce)',
                'code' => 'XAU',
                'notes' => null,
            ],
            [
                'currency_id' => 160,
                'name' => 'East Caribbean Dollar',
                'code' => 'XCD',
                'notes' => null,
            ],
            [
                'currency_id' => 161,
                'name' => 'Special Drawing Rights',
                'code' => 'XDR',
                'notes' => null,
            ],
            [
                'currency_id' => 162,
                'name' => 'CFA Franc BCEAO',
                'code' => 'XOF',
                'notes' => null,
            ],
            [
                'currency_id' => 163,
                'name' => 'CFP Franc',
                'code' => 'XPF',
                'notes' => null,
            ],
            [
                'currency_id' => 164,
                'name' => 'Yemeni Rial',
                'code' => 'YER',
                'notes' => null,
            ],
            [
                'currency_id' => 165,
                'name' => 'South African Rand',
                'code' => 'ZAR',
                'notes' => null,
            ],
            [
                'currency_id' => 166,
                'name' => 'Zambian Kwacha (pre-2013)',
                'code' => 'ZMK',
                'notes' => null,
            ],
            [
                'currency_id' => 167,
                'name' => 'Zambian Kwacha',
                'code' => 'ZMW',
                'notes' => null,
            ],
            [
                'currency_id' => 168,
                'name' => 'Zimbabwean Dollar',
                'code' => 'ZWL',
                'notes' => null,
            ],
        ]);
    }
}
