<?php

namespace Database\Seeders;

use App\Models\Notifications;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class NotificationsSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Notifications::insert([
            [
                'notification_id' => 312,
                'name' => 'Member Birthday',
                'status' => 'enabled',
                'emailSubject' => 'Happy Birthday',
                'emailContent' => '<p>Happy birthday [member_name]!</p><p>We wish you all the best on your special day</p>',
                'system_type' => 'editable',
                'system_context' => 'birthday',
                'description' => "Sent to member. Occurs on a member's birthday.",
                'email_index' => null,
                'unsubscribable' => null,
            ],
            [
                'notification_id' => 10005,
                'name' => 'Member Birthday',
                'status' => 'enabled',
                'emailSubject' => 'Birthday Reminder:  [member_name] - Octiv',
                'emailContent' => "Hi <strong>[coach_name] [coach_surname]</strong>,\n<br />\n<br />\nToday is [member_name] [member_surname] Birthday.<br />",
                'system_type' => 'editable',
                'system_context' => 'birthday_reminder',
                'description' => "Sent to staff. Occurs on a member's birthday.",
                'email_index' => 'Birthdays|home|reminder|51',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10006,
                'name' => 'Contract Expiry',
                'status' => 'enabled',
                'emailSubject' => 'Contract Expiring for:  [member_name] - Octiv',
                'emailContent' => "Hi <strong>[coach_name]</strong>,\n<br />\n<br />\nThe contract for [member_name] [member_surname] is going to expire in the next [expiry_notification_days] days.<br />\n<br />\n<u>Contract DETAILS:</u><br />\nMember name:  [member_name] [member_surname] <br />\nMember email: [member_email]<br />\nMember mobile number: [member_mobile]<br />\nExpiry date: [expiry_date]<br />",
                'system_type' => 'editable',
                'system_context' => 'contract_expiry_noitification',
                'description' => "Sent to staff. Occurs when a member's contract is reaching it's expiry date.",
                'email_index' => 'Contracts|contracts|expiry_notification|99',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10007,
                'name' => 'Accept Contract Terms And Conditions',
                'status' => 'enabled',
                'emailSubject' => 'Accept contract terms',
                'emailContent' => "Hi <strong> [member_name] [member_surname]</strong>,\n<br />\n<br />\nPlease click on the link below to agree to the contract.\n<br />\n<br />\nContract Link: [link]\n",
                'system_type' => 'editable',
                'system_context' => 'accept_terms',
                'description' => 'Sent to member.',
                'email_index' => 'Contracts|contracts|sendContract|130',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10008,
                'name' => 'Send: Contract',
                'status' => 'enabled',
                'emailSubject' => 'Sign Contract',
                'emailContent' => "Hi <strong> [member_name] [member_surname]</strong>,\n<br />\n<br />\nHi please find contract document/s attached.<br />\n<br />",
                'system_type' => 'editable',
                'system_context' => 'sign_contract',
                'description' => 'Sent to member. Occurs when a contract is sent.',
                'email_index' => 'Contracts|contracts|sendContractAttachment|172',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10010,
                'name' => 'Send: Statement',
                'status' => 'enabled',
                'emailSubject' => 'Statement [start_date] [end_date]',
                'emailContent' => '[message]',
                'system_type' => 'editable',
                'system_context' => 'send_statement',
                'description' => 'Sent to member. Occurs when a statement is sent.',
                'email_index' => 'Finance|statement|email|162',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10011,
                'name' => 'Send: Invoice',
                'status' => 'enabled',
                'emailSubject' => 'Invoice for: [member_name] [member_surname] ',
                'emailContent' => "Hi <strong>[member_name] [member_surname] </strong>,\n<br />\n<br />\nPlease find your invoice attached to this email.\n<br />\n<br />",
                'system_type' => 'editable',
                'system_context' => 'send_invoice',
                'description' => 'Sent to member. Occurs when an invoice is sent.',
                'email_index' => 'Finance|user_invoice|email_invoice|1949',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10012,
                'name' => 'Injury: Logged By Member',
                'status' => 'enabled',
                'emailSubject' => 'New Injury Logged by Member',
                'emailContent' => 'Hi [coach_name] [coach_surname],<br /><br />[member_name] [member_surname] has logged an injury:<br /><br />[injury_update_content]',
                'system_type' => 'admin',
                'system_context' => 'add_injury_athlete',
                'description' => 'Sent to staff. Occurs when a member logs an injury.',
                'email_index' => 'Injuries|athlete|add|79',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10013,
                'name' => 'Injury: Updated By Member',
                'status' => 'enabled',
                'emailSubject' => 'Injury Updated',
                'emailContent' => 'Hi [coach_name],<br /><br />[member_name] [member_surname] has updated an injury:<br /><br />[injury_update_content]',
                'system_type' => 'admin',
                'system_context' => 'update_injury_athlete',
                'description' => 'Sent to staff. Occurs when a member updates an injury.',
                'email_index' => 'Injuries|athlete|update|120',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10014,
                'name' => 'Injury: Healed By Member',
                'status' => 'enabled',
                'emailSubject' => 'Injury Marked As Healed',
                'emailContent' => 'Hi [coach_name],<br /><br />[member_name] [member_surname] marked an injury as healed:<br /><br />[injury_update_content]',
                'system_type' => 'admin',
                'system_context' => 'heal_injury_athlete',
                'description' => 'Sent to staff. Occurs when a member marks an injury as healed.',
                'email_index' => 'Injuries|athlete|heal|179',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10015,
                'name' => 'Injury: Logged By Trainer',
                'status' => 'enabled',
                'emailSubject' => 'Injury Logged',
                'emailContent' => 'Hi [member_name] [member_surname],<br /><br />[coach_name] [coach_surname] has logged an injury on your behalf:<br /><br />[injury_update_content]',
                'system_type' => 'admin',
                'system_context' => 'add_injury_coach',
                'description' => 'Sent to member. Occurs when a trainer logs an injury.',
                'email_index' => 'Injuries|athlete|add|81',
                'unsubscribable' => 1,
            ],
            [
                'notification_id' => 10016,
                'name' => 'Injury: Updated By Trainer',
                'status' => 'enabled',
                'emailSubject' => 'Injury Updated',
                'emailContent' => 'Hi [member_name],<br /><br />[coach_name] [coach_surname] has updated an injury on your behalf:<br /><br />[injury_update_content]',
                'system_type' => 'admin',
                'system_context' => 'update_injury_coach',
                'description' => 'Sent to member. Occurs when a trainer updates an injury.',
                'email_index' => 'Injuries|athlete|update|120',
                'unsubscribable' => 1,
            ],
            [
                'notification_id' => 10017,
                'name' => 'Injury: Healed By Trainer',
                'status' => 'enabled',
                'emailSubject' => 'Injury Marked As Healed',
                'emailContent' => 'Hi [member_name],<br /><br />[coach_name] [coach_surname] marked your injury as healed:<br /><br />[injury_update_content]',
                'system_type' => 'admin',
                'system_context' => 'heal_injury_coach',
                'description' => 'Sent to member. Occurs when a trainer marks an injury as healed.',
                'email_index' => 'Injuries|box|heal|182',
                'unsubscribable' => 1,
            ],
            [
                'notification_id' => 10018,
                'name' => 'Send: Waiver',
                'status' => 'enabled',
                'emailSubject' => 'Sign Waiver',
                'emailContent' => "Hi <strong>[member_name] [member_surname]</strong>,\n<br />\n<br />\nPlease click on the link below to agree to the terms and conditions for the waiver.\n<br />\n<br />\nWaiver Link: [link]\n<br />",
                'system_type' => 'editable',
                'system_context' => 'send_waiver',
                'description' => 'Sent to member. Occurs when a waiver is sent.',
                'email_index' => 'Leads|members|send_waiver|657',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10024,
                'name' => 'Task: Assigned',
                'status' => 'enabled',
                'emailSubject' => 'New task - Octiv',
                'emailContent' => "Hi <strong>[coach_name] [coach_surname]</strong>,\n<br />\n<br />\nYou have being assigned to a new task.\n<br />\n<br />\n<u>Task Details:</u><br />\nTask name: [task_name]<br />\nTask time: [task_time]<br />\nTask date: [task_date]<br />\nTask description: [task_description]<br />",
                'system_type' => 'editable',
                'system_context' => 'new_task',
                'description' => 'Sent to task assignee. Occurs when a new task is created.',
                'email_index' => 'Tasks|tasks|edit|272',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10025,
                'name' => 'Task: Removed as Assigned',
                'status' => 'enabled',
                'emailSubject' => 'Task Removal - Octiv',
                'emailContent' => "Hi <strong>[coach_name] [coach_surname]</strong>,\n<br />\n<br />\nYou have being removed from a task.\n<br />\n<br />\n<u>Task Details:</u><br />\nTask name: [task_name]<br />\nTask time: [task_time]<br />\nTask date: [task_date]<br />\nTask description: [task_description]<br />",
                'system_type' => 'editable',
                'system_context' => 'task_removal',
                'description' => 'Sent to task assignee. Occurs when an assignee gets removed from a task.',
                'email_index' => 'Tasks|tasks|edit|317',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10028,
                'name' => 'Box activation',
                'status' => 'enabled',
                'emailSubject' => 'Box activation - Octiv',
                'emailContent' => "Hi <strong>[coach_name] [coach_surname]</strong>,\n<br />\n<br />\nYour Box has been activated.\n<br />\n<br />\nYour password: [password]</strong>\n<br />\n<br />",
                'system_type' => 'admin',
                'system_context' => 'box_activation',
                'description' => '',
                'email_index' => 'boxes|index|150',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10029,
                'name' => 'Class Booking: No Show',
                'status' => 'enabled',
                'emailSubject' => 'Message from coach: [class_name] - Octiv',
                'emailContent' => "Hi <strong>[member_name] [member_surname]</strong>,\n<br />\n<br />\nWe hope everything is ok.\n<br />\n<br />\nPlease note that you booked and didn't cancel your booking, therefore it will count towards your attendance. \n<br />\nPlease could you cancel your booking in future or let us know if there is a problem.\n<br />\n<br />\n<u>CLASS DETAILS:</u><br />\nClass name: [class_name]<br />\nClass time: [class_time]<br />\nClass date: [class_booking_date]<br />\nThanks <br />\nCoach\n\n<p>Regards,<br />Team Octiv<br />",
                'system_type' => 'editable',
                'system_context' => 'no_show',
                'description' => 'Sent to member. Occurs when a booking is marked as no show.',
                'email_index' => 'Classes|no_show|1284',
                'unsubscribable' => 1,
            ],
            [
                'notification_id' => 10030,
                'name' => 'Class Booking: Booked From Waiting List (Created By Trainer)',
                'status' => 'enabled',
                'emailSubject' => 'Your booking confirmation: [class_name] - Octiv',
                'emailContent' => "Hi <strong>[member_name]</strong>,\n<br />\n<br />\nAn athlete has just cancelled their booking for a class that has you on it's waiting list. So you have automaticlly been booked into this class.\n<br />\n<br />\nYour booking has been confirmed.\n<br />\n<br />\n<u>CLASS DETAILS:</u><br />\nClass name: [class_name]<br />\nClass time: [class_time]<br />\nClass date: [class_booking_date]<br />",
                'system_type' => 'editable',
                'system_context' => 'delete_booking',
                'description' => 'Sent to member. Occurs when a member is booked into a class from the waiting list.',
                'email_index' => 'Classes|deletebooking|1466',
                'unsubscribable' => 1,
            ],
            [
                'notification_id' => 10031,
                'name' => 'Message From Trainer To Class',
                'status' => 'enabled',
                'emailSubject' => 'Message From Trainer: [class_name]',
                'emailContent' => 'Hi [member_name] [member_surname],<br /><br />A message has been sent by your trainer, [coach_name] [coach_surname]:<br /><br />[coach_message]<br /><br /><u>CLASS DETAILS:</u><br />Name: [class_name]<br />Time: [class_time]<br />Date: [class_booking_date]',
                'system_type' => 'admin',
                'system_context' => 'member_message',
                'description' => 'Sent to attendees. Occurs when a message is sent to class attendees.',
                'email_index' => 'Classes|membermessage|1552',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10032,
                'name' => 'Message From Trainer To Class (Copy)',
                'status' => 'enabled',
                'emailSubject' => 'Copy of message to attendees: [class_name]',
                'emailContent' => 'Hi [coach_name] [coach_surname],<br /><br />Your message has been sent:<br /><br /><i>[coach_message]</i><br /><br /><u>CLASS DETAILS:</u><br />Name: [class_name]<br />Time: [class_time]<br />Date: [class_booking_date]',
                'system_type' => 'admin',
                'system_context' => 'confirmation_member_message',
                'description' => 'Sent to trainer. Occurs when a message is sent to class attendees.',
                'email_index' => 'Classes|membermessage|1570',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10033,
                'name' => 'Message From Class Attendee To Trainer',
                'status' => 'enabled',
                'emailSubject' => 'Message Sent By Class Attendee',
                'emailContent' => 'Hi,<br /><br />A message has been sent by [member_name] [member_surname]:<br /><br /><i>[member_message]</i><br /><br /><u>CLASS DETAILS:</u><br />Name: [class_name]<br />Time: [class_time]<br />Date: [class_booking_date]',
                'system_type' => 'admin',
                'system_context' => 'coach_message',
                'description' => 'Sent to staff. Occurs when a class attendee sends a message.',
                'email_index' => 'Classes| coachmessage |1632',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10035,
                'name' => 'Class Booking: Confirmation',
                'status' => 'enabled',
                'emailSubject' => 'Your booking confirmation: [class_name] - Octiv',
                'emailContent' => "Hi <strong>[member_name] [member_surname]</strong>,<br /><br />\nYour booking has been confirmed.<br /><br />\n<u>CLASS DETAILS:</u><br />\nClass name: [class_name]<br />\nClass time: [class_time]<br />\nClass date: [class_booking_date]<br />",
                'system_type' => 'editable',
                'system_context' => 'book_class',
                'description' => 'Sent to member. Occurs when a class is booked.',
                'email_index' => 'Classes|bookClass|1804',
                'unsubscribable' => 1,
            ],
            [
                'notification_id' => 10036,
                'name' => 'Class Booking: Booked From Waiting List (Created By Member)',
                'status' => 'enabled',
                'emailSubject' => 'Your booking confirmation: [class_name] - Octiv',
                'emailContent' => "Hi <strong>[member_name] [member_surname]</strong>,<br /><br />\nAn athlete has just cancelled their booking for a class that has you on it's waiting list. So you have automatically been booked into this class.<br /><br />\nYour booking has been confirmed.<br /><br />\n<u>CLASS DETAILS:</u><br />\nClass name: [class_name]<br />\nClass time: [class_time]<br />\nClass date: [class_booking_date]<br />",
                'system_type' => 'editable',
                'system_context' => 'waitinglist_booking',
                'description' => 'Sent to member. Occurs when a member is booked into a class from the waiting list.',
                'email_index' => 'Classes|cancelClass|2065',
                'unsubscribable' => 1,
            ],
            [
                'notification_id' => 10037,
                'name' => 'Class Booking: Booked From Waiting List',
                'status' => 'enabled',
                'emailSubject' => 'Booking cancellation & confirmation: [class_name] - Octiv',
                'emailContent' => "Hi <strong>Coach</strong>,<br /><br />\nAn athlete has just cancelled their booking. One of the athletes on the waiting list has been notified and booked into the class<br /><br />\n<u>CLASS DETAILS:</u><br />\nClass name: [class_name]<br />\nClass time: [class_time]<br />\nClass date: [class_booking_date]<br />\nCanceled booking athlete: [member_name] [member_surname]<br />\nNew booking athlete: [waiting_member_name] [waiting_member_surname]<br />",
                'system_type' => 'editable',
                'system_context' => 'coach_cancel_message_waitinglist',
                'description' => 'Sent to staff. Occurs when a member is booked into a class from the waiting list.',
                'email_index' => 'Classes|cancelClass|2111',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10038,
                'name' => 'Class Booking: Cancelled',
                'status' => 'enabled',
                'emailSubject' => 'Booking cancellation: [class_name] - Octiv',
                'emailContent' => "Hi <strong>Coach</strong>,<br /><br />\nAn athlete has just cancelled their booking.<br /><br />\n\n[cancel_threshold_message]\n\n<u>CLASS DETAILS:</u><br />\nClass name: [class_name]<br />\nClass time: [class_time]<br />\nClass date: [class_booking_date]<br />\nAthlete: [member_name] [member_surname]\"<br />",
                'system_type' => 'editable',
                'system_context' => 'coach_cancel_message',
                'description' => 'Sent to staff. Occurs when a member cancels a booking.',
                'email_index' => 'Classes|cancelClass|2142',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10039,
                'name' => 'Class Booking: Cancelled',
                'status' => 'enabled',
                'emailSubject' => 'Your booking cancellation: [class_name] - Octiv',
                'emailContent' => "Hi <strong>[member_name] [member_surname]</strong>,<br /><br />\nYour booking has been cancelled.<br /><br />\n\n[cancel_threshold_message]\n\n<u>CLASS DETAILS:</u><br />\nClass name: [class_name]<br />\nClass time: [class_time]<br />\nClass date: [class_booking_date]<br />\n",
                'system_type' => 'editable',
                'system_context' => 'cancel_class',
                'description' => 'Sent to member. Occurs when a member cancels a booking.',
                'email_index' => 'Classes|cancelClass|2178',
                'unsubscribable' => 1,
            ],
            [
                'notification_id' => 10043,
                'name' => 'Class Update: Discontinued Recurring Class Day',
                'status' => 'enabled',
                'emailSubject' => 'Class day discontinued: [class_name] - Octiv',
                'emailContent' => "Hi <strong>[member_name] [member_surname]</strong>,<br /><br />\nThis is to notify you that a class you had previously booked has has been discontinued and thus, your booking has been cancelled.\n<u>CLASS DETAILS:</u><br />\nClass name: [old_class_name]<br />\nClass date:  [old_class_date]<br />",
                'system_type' => 'editable',
                'system_context' => 'class_day_discontinued',
                'description' => 'Sent to member. Occurs when a day is removed from a recurring class and their booking is cancelled.',
                'email_index' => 'Classes|update|3723',
                'unsubscribable' => 1,
            ],
            [
                'notification_id' => 10044,
                'name' => 'Class Update: Schedule Changed',
                'status' => 'enabled',
                'emailSubject' => 'Class schedule change: [class_name] - Octiv',
                'emailContent' => "<html>\n<head>\n\t<title></title>\n</head>\n<body>\n<p>Hi <strong>[member_name] [member_surname]</strong>,<br />\n<br />\nThis is to notify you that a class you have booked has been modified. <u>CLASS DETAILS:</u><br />\nClass name: [class_name]<br />\nClass date: [class_date]<br />\nOld time: [class_old_time]<br />\nNew time: [class_new_time]<br />\n[class_coach]<br />\n<br />\nPlease cancel your booking for this class if the new schedule does not suit you.</p>\n</body>\n</html>",
                'system_type' => 'editable',
                'system_context' => 'class_schedule_change',
                'description' => 'Sent to member. Occurs when a class schedule is changed.',
                'email_index' => 'Classes|updateSingle|4017',
                'unsubscribable' => 1,
            ],
            [
                'notification_id' => 10045,
                'name' => 'Class Update: Discontinued',
                'status' => 'enabled',
                'emailSubject' => 'Class discontinued: [class_name] - Octiv',
                'emailContent' => "Hi <strong>[member_name]</strong>,<br /><br />\nThis is to notify you that a class you were participating in has just been discontinued.<br /><br />\n<u>CLASS DETAILS:</u><br />\nClass name: [class_name]<br />\nClass date: [class_date]<br />",
                'system_type' => 'editable',
                'system_context' => 'class_discontinued',
                'description' => 'Sent to member. Occurs when a class is deleted.',
                'email_index' => 'Classes|deleteSingle|4338',
                'unsubscribable' => 1,
            ],
            [
                'notification_id' => 10048,
                'name' => 'Password Updated',
                'status' => 'enabled',
                'emailSubject' => 'Password Updated',
                'emailContent' => 'Hi [member_name] [member_surname],<br /><br />This is to confirm that you recently changed your password',
                'system_type' => 'admin',
                'system_context' => 'change_password_user',
                'description' => 'Sent to member. Occurs when a member updates their password.',
                'email_index' => 'Profile|index|120 && Settings|index|118',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 10050,
                'name' => 'Workout Result: New Comment',
                'status' => 'enabled',
                'emailSubject' => 'New comment on wod - Octiv',
                'emailContent' => "Hi <strong>[wodcapture_user_name] [wodcapture_user_surname]</strong>,\n<br />\n<br />\n<strong>[member_name] [member_surname]</strong> has commented on your wod: [wod_name]<br />\n<br />\n<p>Comment: [comment]</p><br />\n",
                'system_type' => 'editable',
                'system_context' => 'wod_comment',
                'description' => 'Sent to member. Occurs when a new comment is made on a workout result.',
                'email_index' => 'Whiteboard|createComment|748',
                'unsubscribable' => 1,
            ],
            [
                'notification_id' => 10053,
                'name' => 'Class Update: Discontinued',
                'status' => 'enabled',
                'emailSubject' => 'Class discontinued: [class_name] - Octiv',
                'emailContent' => "Hi <strong>[coach_name]</strong>,<br /><br />\nThis is to notify you that a class you were participating in has just been discontinued.<br /><br />\n<u>CLASS DETAILS:</u><br />\nClass name: [class_name]<br />\nClass date: [class_date]<br />",
                'system_type' => 'editable',
                'system_context' => 'coach_class_discontinued',
                'description' => 'Sent to staff. Occurs when a class is deleted.',
                'email_index' => 'Classes|deleteSingle|4338',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 16855,
                'name' => 'Send: Waiver With Attachment',
                'status' => 'enabled',
                'emailSubject' => 'Sign Waiver',
                'emailContent' => "Hi <strong>[member_name] [member_surname]</strong>,\r\n<br />\r\n<br />\r\nPlease find your waiver attached.\r\n<br />\r\n<br />",
                'system_type' => 'editable',
                'system_context' => 'send_waiver_attachment',
                'description' => 'Sent to member. Occurs when a waiver is sent with an attachment.',
                'email_index' => 'Leads|members|send_waiver|657',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 18264,
                'name' => 'Lead Member Registration Confirmation',
                'status' => 'enabled',
                'emailSubject' => 'You enquiry is being processed',
                'emailContent' => "Hi <strong>[member_name] [member_surname]</strong>,\n<br />\n<br />\nYour enquiry has been sent, a box representative will contact you soon.\n<br />\n<br />",
                'system_type' => 'editable',
                'system_context' => 'member_lead_received',
                'description' => 'Sent to lead. Occurs when a new lead registers via the lead widget.',
                'email_index' => '',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 19844,
                'name' => 'Welcome Message',
                'status' => 'enabled',
                'emailSubject' => 'Welcome to [box_name]',
                'emailContent' => "<p>Hi [user_name],</p>\n\n<p>&nbsp;</p>\n\n<p>[intro_text]</p>\n\n<ul>\n\t<li>View your gym&#39;s schedule and book your sessions</li>\n\t<li>Track your fitness training and see when you&#39;re making progress</li>\n\t<li>Track injuries, payments, interact with peers</li>\n\t<li>and so much more</li>\n</ul>\n\n<p>To login to your profile:</p>\n\n<ol>\n\t<li>Download the Octiv app:</br>iOS: <a href=\"https://apps.apple.com/za/app/octiv/id1533669918\" target=\"_blank\">https://apps.apple.com/za/app/octiv/id1533669918</a></br> Android: <a href=\"https://play.google.com/store/apps/details?id=com.octiv.mobile\" target=\"_blank\">https://play.google.com/store/apps/details?id=com.octiv.mobile</a></br> Huawei: <a href=\"https://appgallery.huawei.com/#/app/C103840907\" target=\"_blank\">https://appgallery.huawei.com/#/app/C103840907</a>&nbsp;</li>\n\t<li>Use your email [user_email] and your unique password [user_password]. You can change your password once logged in under My Profile > Password.</li>\n</ol>\n\n<p>Enjoy your training!</p>\n",
                'system_type' => 'admin',
                'system_context' => 'welcome_message',
                'description' => 'Global welcome massage that containes 2 attachments one from the box and one from boxchamp. This message only gets sent once a user is created and activated.',
                'email_index' => null,
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 28168,
                'name' => 'Contract Expiry',
                'status' => 'enabled',
                'emailSubject' => 'Contract Expiring for:  [member_name] - Octiv',
                'emailContent' => "Hi <strong>[member_name] [member_surname]</strong>,\n<br />\n<br />\nYour contract is going to expire in the next [expiry_notification_days] days.<br />\n<br />\n<u>Contract DETAILS:</u><br />\nMember name:  [member_name] [member_surname] <br />\nMember email: [member_email]<br />\nMember mobile number: [member_mobile]<br />\nExpiry date: [expiry_date]<br />",
                'system_type' => 'editable',
                'system_context' => 'contract_expiry_member_notification',
                'description' => "Sent to member. Occurs when a member's contract is reaching it's expiry date.",
                'email_index' => 'Contracts|contracts|expiry_notification|99',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 29373,
                'name' => 'Lead Member Registration Confirmation (Demo)',
                'status' => 'enabled',
                'emailSubject' => 'You enquiry is being processed',
                'emailContent' => "Hi <strong>[member_name] [member_surname]</strong>,\n<br />\n<br />\nYour enquiry has been sent, a box representative will contact you soon.\n<br />\n<br />",
                'system_type' => 'editable',
                'system_context' => 'member_lead_received_demo_request',
                'description' => 'Sent to lead. Occurs when a new lead registers via the lead demo widget.',
                'email_index' => '',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 29667,
                'name' => 'New Drop-In',
                'status' => 'enabled',
                'emailSubject' => 'Drop-in confirmation',
                'emailContent' => "Hi <strong>Coach</strong>,\n<br />\n<br />\nA new lead has purchased [sessions_purchased] drop-in session(s) using the widget. Here is the lead's information:\n<br />\n<br />\nLocation: [location_name]<br />\nName: [member_name] [member_surname]<br />\nEmail: [member_email]<br />\nDate of birth: [member_dob]<br />\nMobile: [member_mobile]<br />\nNotes: [member_notes]\n<br />\n<br />",
                'system_type' => 'editable',
                'system_context' => 'drop_in_confirmation_coach',
                'description' => 'Sent to staff. Occurs when a drop-in is created via the drop-in widget.',
                'email_index' => '',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 29668,
                'name' => 'New Drop-In',
                'status' => 'enabled',
                'emailSubject' => 'Drop-in confirmation',
                'emailContent' => "Hi <strong>[member_name] [member_surname]</strong>,\n<br />\n<br />\nWell done on successfully purchasing [sessions_purchased] drop-in session(s) at [location_name]. If you haven't booked all your sessions yet, then you can click the link below to book the rest of them:\n<br />\n<br />\n[booking_link]\n<br />\n<br />",
                'system_type' => 'editable',
                'system_context' => 'drop_in_confirmation_member',
                'description' => 'Sent to drop-in. Occurs when a drop-in is created via the drop-in widget.',
                'email_index' => '',
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 29735,
                'name' => 'New lead referred by member',
                'status' => 'enabled',
                'emailSubject' => 'New lead: referred by member',
                'emailContent' => "<html>\n<head>\n\t<title></title>\n</head>\n<body>\n<p>Hi coach,</p>\n<p>&nbsp;</p>\n<p>A member has referred a friend.</p>\n\n<p>&nbsp;</p>\n\n<p>Lead details:</p>\n\n<p>Name: [name] [surname]</p>\n\n<p>Email: [email]</p>\n\n<p>Mobile number: [mobile]</p>\n\n<p>Location: [location]</p>\n\n<p>Notes: [notes]</p>\n</body>\n</html>\n",
                'system_type' => 'admin',
                'system_context' => 'new_referred_lead',
                'description' => 'Message sent to coach when a new lead is referred by member',
                'email_index' => null,
                'unsubscribable' => 0,
            ],
            [
                'notification_id' => 33828,
                'name' => 'Sign Up: Immediately',
                'status' => 'disabled',
                'emailSubject' => null,
                'emailContent' => null,
                'system_type' => 'editable',
                'system_context' => 'sign_up_immediately',
                'description' => 'Sent to member. Occurs immediately after a member signs up.',
                'email_index' => null,
                'unsubscribable' => null,
            ],
            [
                'notification_id' => 33829,
                'name' => 'Sign Up: 2 Weeks',
                'status' => 'disabled',
                'emailSubject' => null,
                'emailContent' => null,
                'system_type' => 'editable',
                'system_context' => 'sign_up_two_weeks',
                'description' => 'Sent to member. Occurs 2 weeks after a member signs up.',
                'email_index' => null,
                'unsubscribable' => null,
            ],
            [
                'notification_id' => 33830,
                'name' => 'Sign Up: 1 Month',
                'status' => 'disabled',
                'emailSubject' => null,
                'emailContent' => null,
                'system_type' => 'editable',
                'system_context' => 'sign_up_one_month',
                'description' => 'Sent to member. Occurs 1 month after a member signs up.',
                'email_index' => null,
                'unsubscribable' => null,
            ],
            [
                'notification_id' => 33831,
                'name' => 'Sign Up: 3 Months',
                'status' => 'disabled',
                'emailSubject' => null,
                'emailContent' => null,
                'system_type' => 'editable',
                'system_context' => 'sign_up_three_months',
                'description' => 'Sent to member. Occurs 3 months after a member signs up.',
                'email_index' => null,
                'unsubscribable' => null,
            ],
            [
                'notification_id' => 33832,
                'name' => 'Sign Up: 6 Months',
                'status' => 'disabled',
                'emailSubject' => null,
                'emailContent' => null,
                'system_type' => 'editable',
                'system_context' => 'sign_up_six_months',
                'description' => 'Sent to member. Occurs 6 months after a member signs up.',
                'email_index' => null,
                'unsubscribable' => null,
            ],
            [
                'notification_id' => 33833,
                'name' => 'Sign Up: 1 Year',
                'status' => 'disabled',
                'emailSubject' => null,
                'emailContent' => null,
                'system_type' => 'editable',
                'system_context' => 'sign_up_one_year',
                'description' => 'Sent to member. Occurs 1 year after a member signs up.',
                'email_index' => null,
                'unsubscribable' => null,
            ],
        ]);
    }
}
